### ISSUE TITLE
Consider include PTS dictionary.

### ISSUE THREAD

**Issue by Nirodhiko** [simsapa/simsapa#10]
Thanks for your project.

I found that the PTS dictionary is of great value, and the explanations of many words are more accurate and precise.
'digitalpalidictionary' is necessary, but it is not enough.

**Comment by gambhiro** [comment]
PTS is included along with these: https://simsapa.github.io/features/dhamma-texts/

The DPD results often come first in the results. To see PTS only, select "Fulltext" search and "PTS" dictionary:

![2024-02-08_07-38](https://github.com/simsapa/simsapa/assets/1586232/b2510d0d-e6fe-43ac-b6d7-dcac306f8868)

**Comment by Nirodhiko** [comment]
@gambhiro 
That's great! I haven't used this reading before because I thought it was only DPD, thank you very much!
