### ISSUE TITLE
RegEx search option in sutta and dictionary

### ISSUE THREAD

**Issue by gambhiro** [simsapa/simsapa#14]
Allow full regex pattern search in the SQL database.

The `[ ] .*` toggle in the search bar is not a full regex engine, the tantivy fulltext engine only supports globbing expressions (`.* .+ a* a+`).

**Comment by gambhiro** [comment]
Commit 25717ca0 adds "Contains Match" and "RegEx Match" options to sutta and dictionary search.

The results are currently not sorted, see #22

"Contains" uses the query as an SQL `%query%` expression.

"RegEx" uses the query with SQLAlchemy `.regexp_match()` method.

"Search As You Type" is disabled for these modes. Press Enter or click the search button to run the query.

To improve the time of RegEx queries, select a Language and Source filter, so that not all database records are scanned for matches.

The search input is split on `AND`, and combines each expression as a filter.

Examples:

`dukkha AND sukha` "Contains Match" means a record has to match:

- `%dukkha%` and
- `%sukha%`

`dukkha AND sukh\w+` "RegEx Match" means a record has to match:

- `dukkha` and
- `sukh\w+`

RegEx starting with `.*` and `.+` have extremely bad performance, hence not allowed. A warning is displayed:

```
RegEx starting with .* or .+ have extremely bad performance and can freeze the
application, hence are not allowed.

Combine them with a more simple AND term to filter the number of texts which
have to be matched, such as:

dukkha AND .+dukkha
```

**Comment by bdhrs** [comment]
yes that works nicely. if you limit the texts, the speed is reasonable as well.

one unintended side effect of having "regex match" on in the dictionary, is when you double-click on a word in a sutta to open it in the dictionary, it performs the regex search, which is quite time consuming. in that case the behaviour is not ideal.
