### ISSUE TITLE
Cli command to update the DPD database manually

### ISSUE THREAD

**Issue by gambhiro** [simsapa/simsapa#19]
Provide a cli command to replace the current DPD in Simsapa from a `dpd.db` generated directly from [dpd-db](https://github.com/digitalpalidictionary/dpd-db).

**Comment by gambhiro** [comment]
The `migrate-and-index-dpd` following cli command will:

- create a copy of the db file
- run the db migration
- copy the migrated db to SIMSAPA_DIR (`~/.local/share/simsapa/assets/dpd.sqlite3`)
- re-generate the dictionary fulltext index for `en` language (which includes the DPD)

```
./Simsapa_Dhamma_Reader-0.5.0a1-x86_64.AppImage migrate-and-index-dpd path/to/dpd.db
```

Check log.txt for watching the progress:

```
tail -s 0.5 -f ~/.local/share/simsapa/log.txt
```

**Comment by bdhrs** [comment]
great! that seems to work. it takes just over 5min on my machine .
