### ISSUE TITLE
No .msi on Releases page?

### ISSUE THREAD

**Issue by thesunshade** [simsapa/simsapa#2]
On the readme page it mentions the existence of an .msi file for installing on Windows. But I don't see it on the [release](https://github.com/simsapa/simsapa/releases/) page. Just wondering if it is available somewhere I'm missing, or if (quite understandably) it's not available at this point.

**Comment by gambhiro** [comment]
The windows build is currently broken. On startup, the app starts a server process for internal communications, and this server thread crashes on windows.

I'm going to debug it eventually and then there will be a windows release again. In November I think I'll have time to continue this project.

**Comment by thesunshade** [comment]
Thanks!
