### ISSUE TITLE
DPD update window too large on Macbook Air 2013

### ISSUE THREAD

**Issue by philaleth3s** [simsapa/simsapa#24]
Hola,

Sorry for the rather niche issue, but:

I run your wonderful software on a 13 inch screen Macbook air. When the DPD update window prompt pop up, the confirmation part runs lower than my screen, and because the window is quite long, I cannot bring it upwards to see the bottom, it just doesn't fit in the screen! Therefore I'm unable to pick to confirm the update. I tried looking at workarounds in Macos and could not find any. If there was some way to make this window resizeable or larger rather than longer or with less text, or to be able to toggle the update from somewhere else, that would be lovely. Hope all is well with you and thanks again for this amazing resource!

**Comment by thesunshade** [comment]
It's not a problem only with Macbooks. I'm on windows on a fairly large screen and still the dialog box goes off the screen. It's a general problem that needs to be fixed by allowing the window to scroll. You could amend your issue title to reflect that.

Thanks for creating the issue!

**Comment by gambhiro** [comment]
Thanks for noting the issue on small screens. I added a condition to truncate long release messages. I am planning a bugfix release soon, including this one.

**Comment by philaleth3s** [comment]
Thank you so much!
