### ISSUE TITLE
network connection timeout error

### ISSUE THREAD

**Issue by vijjo** [simsapa/simsapa#5]
After opening, the app shows the following error when trying to down database:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/31264468/232225671-b59d39bf-d5d9-4bcf-b0b6-e38ccf45047e.png">

The app looks awesome. I'm looking forward to try it!

**Comment by gambhiro** [comment]
Thanks for the notice.

It seems to have started up fine, but the network request to get the list of database files didn't succeed.

Could it be that a firewall or a security setting is blocking network requests from the app?

**Comment by gambhiro** [comment]
Did you find out what was blocking the network request?

If necessary, it's not too difficult to download the database manually. The assets are here:

https://github.com/simsapa/simsapa-assets/releases/tag/v0.3.0-alpha.1

You need at least three files:

- appdata.tar.bz2
- index.tar.bz2
- userdata.tar.bz2

Move them to the app's data folder. On a Mac it is:

```
cd ~/Library/Application\ Support/simsapa/
ls
assets/  log.txt

# Remove any existing assets
rm -r assets/ log.txt
mkdir assets
cd assets

# move the downloaded files here and extract
mv ~/Downloads/*.tar.bz2
tar xjf *.tar.bz2

# remove the archives
rm *.tar.bz2

# Still in 'assets' folder, the contents should look like:
ls
appdata.sqlite3  courses/  html_resources/  index/  userdata.sqlite3
```

After this, when you start the app, it should find the database.

**Comment by vijjo** [comment]
Thank you for the prompt response!

> Could it be that a firewall or a security setting is blocking network requests from the app?

It might be, but I don't know which caused the blocking.

I followed your instruction and was able to get the app running. However, there were no sutta databases. Should I manually download sutta databases also? Where should I extract those files?

**Comment by gambhiro** [comment]
appdata.sqlite3 includes English and Pali by default. Are these not working in the Sutta Search window?

The Suttas > Sutta Languages menu can be used to add other languages. Try opening that menu, it will again try to retrieve the url which wasn't working, and if it errors, please copy the contents of `~/Library/Application\ Support/simsapa/simsapa/log.txt` here.

**Comment by paladhammika** [comment]
Ajahn,

Could you add these instructions for installing the database manually into the README?

**Comment by paladhammika** [comment]
Ajahn,

Could you add these instructions for installing the database manually into the README?

**Comment by gambhiro** [comment]
@paladhammika Did you also have a similar issue? I haven't seen it on the systems I tested with, it would be good to find out if the cause is in the app, some OS setting, etc.

I'll be adding some docs to https://simsapa.github.io/ , this can go somewhere there as well.

**Comment by paladhammika** [comment]
I helped another venerable who was having the same issue albeit on Linux Mint.

I'm unable to install due to having an older version of GLIBC. Using LMDE (so Debian Stable).

**Comment by gambhiro** [comment]
@paladhammika Does the URL https://simsapa.a-buddha-ujja.hu/releases.php work for you in the browser? I wonder if it times out because of the distance to Malaysia.

Re: glibc, there is always the option to clone the repo and run it from source https://simsapa.github.io/development/running-from-source/

**Comment by gambhiro** [comment]
Please try v0.3.3, I believe it fixes the problem where a network timeout breaks the asset download window.

https://github.com/simsapa/simsapa/releases/tag/v0.3.3-alpha.1

You could verify that it works either by opening the Sutta Languages window and adding some languages, or renaming/removing the app's data folder and starting the setup again.

The steps for manual database setup are now in the docs:

https://simsapa.github.io/development/manual-database-setup/
