### ISSUE TITLE
Can't start AppImage on gentoo linux.

### ISSUE THREAD

**Issue by Nirodhiko** [simsapa/simsapa#7]
Is there a dependent database that I need to install ?

![last](https://github.com/simsapa/simsapa/assets/8435488/aa2a12bb-4f4f-4fdf-ac5d-7c51a07832bd)

**Comment by gambhiro** [comment]
Yes, the first window checks for the latest db version, then it should show a Download button.

Is it stuck at that message? Perhaps the HTTP request to get the db list failed somehow.

It is not difficult to setup the db manually, see if this helps: [Manual Database Setup](https://simsapa.github.io/development/manual-database-setup/)

I would be interested in finding out why the HTTP request failed.

There should be a log file at `~/.local/share/simsapa/log.txt`, that could be helpful if you could attach it here.
