### ISSUE TITLE
v0.4.0 on Intel x86 MacOS crashes with threading errors

### ISSUE THREAD

**Issue by mettavi** [simsapa/simsapa#8]
Hi, there is no Intel Mac version for the last two releases? ;)

**Comment by gambhiro** [comment]
Starting from v0.4.0 the fulltext search engine is the Rust-based [tantivy](https://github.com/quickwit-oss/tantivy).

It's been great, except that on Intel x86 MacOS it crashes with threading errors.

I intend to look into it sometime whether it is possible to fix.

**Comment by mettavi** [comment]
Thanks a lot for the reply.

So to clarify, is it only 32-bit MacOS that has the problem, or 64-bit too (x86 often means 32-bit)?

If there is no binary package I am prepared to try compiling it from source if that is a possible option.

Thanks again. 🙏

**Comment by gambhiro** [comment]
Perhaps running it from source could work. For MacOS, the steps in brief:

- Install [brew.sh](https://brew.sh/), then Python 3.11 with `brew install python@3.11`
- Install [Poetry](https://python-poetry.org/docs/#installation)
- Clone the simsapa repo
-  `cd simsapa` and run `python3 -m poetry install` to install the Python packages

In the project root, enter a virtual environment with poetry and start the app with:

```
python3 -m poetry shell
python3 run.py
```

**Comment by gambhiro** [comment]
I tried building it with macos-13 instead of macos-12. Could you try if this works for you?

https://github.com/simsapa/simsapa/suites/16822417266/artifacts/960767255

**Comment by mettavi** [comment]
Thank you, it took a few minutes to install but it all worked! I am on 13.6. 
I'll have a play with it!

**Comment by gambhiro** [comment]
That's a relief, thanks for testing. I added again the MacOS Intel dmg in the releases.
